### ISSUE TITLE
Delete videos when deleting a Tutorial

### ISSUE THREAD

**Issue by scottalexandra** [MackHalliday/brownfield-of-dreams#5]
Background: Currently deleting a Tutorial will leave all of the videos in the database, meaning they will be referencing a tutorial that doesn't exist.

Use ActiveRecords dependent destroy functionality to fix this.

**Comment by MackHalliday** [comment]
- Completed user story merged into Master 
- Will close ticket once Heroku is updated

**Comment by MackHalliday** [comment]
- Admin cannot delete tutorial in '/admin/dashboard`
- Updating and writing test
- Need to deploy to Heroku
