### ISSUE TITLE
Tutorial show page won't load if missing videos

### ISSUE THREAD

**Issue by scottalexandra** [MackHalliday/brownfield-of-dreams#8]
If a tutorial doesn't have any videos and we visit its show page an error occurs when trying to call `current_video.title` since `current_video` is nil.

A possible easy fix is to default to `Video.new` if there aren't any videos associated with the tutorial.

**Comment by MackHalliday** [comment]
- Need to add sad path
- Possibly include message 'No videos available at this time' or something similar

**Comment by MackHalliday** [comment]
- Created PR for this user story issues 
- Created logic to not show videos if @facade.videos.empty? (facade.videos returns an empty array)

**Comment by MackHalliday** [comment]
- Tested in Heroku OK
